#thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
# druid
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#static
    resources:
      chain:
        cache: true
        gzipped: true
        html-application-cache: true
        enabled: true
      add-mappings: true
      static-locations: classpath:/static/
      cache-period: 3600
#rabbitmq
    rabbitmq:
      template:
        retry:
          max-interval: 10000
          multiplier: 1.0
          max-attempts: 3
          initial-interval: 1000
          enabled: true
      password: guest
      port: 5672
      listener:
        simple:
          default-requeue-rejected: true
          prefetch: 1
          auto-startup: true
          max-concurrency: 10
          concurrency: 10
      host: 10.110.3.62
      virtual-host: /
      username: guest
#redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3
    poolMaxTotal: 10
    poolMaxWait: 3
    poolMaxIdle: 10
#mybatis
mybatis:
  type-aliases-package: top.catalinali.seckill.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:top/catalinali/seckill/dao/*.xml

